### PR TITLE
Remote db connect

### PR DESCRIPTION
**Pull request by AndrooTheChen**
Enable other developers to run a local instance of REMi and connect to the main database remotely (assuming proper authentication is present).

### CODE REVIEW

**Comment by AndrooTheChen** [comment]
> Please add a detailed guide on how to setup your local dev environment to connect to the remote DB in the "Setup" section of the README.

Forgive my inexperience with this, but does it really make sense to give setup instructions to connect to our _private_ database on a _public_ README?

I have the instructions and the authorization tokens shared with internal collaborators  at the moment, and I feel if I only include just the instructions publicly it would be confusing to external collaborators.

Am I miss understanding something here?

**Comment by AndrooTheChen** [comment]
> > Please add a detailed guide on how to setup your local dev environment to connect to the remote DB in the "Setup" section of the README.
> 
> Forgive my inexperience with this, but does it really make sense to give setup instructions to connect to our _private_ database on a _public_ README?
> 
> I have the instructions and the authorization tokens shared with internal collaborators at the moment, and I feel if I only include just the instructions publicly it would be confusing to external collaborators.
> 
> Am I misunderstanding something here?

As a compromise I suppose I could try making a private Wiki page, would that be of any help?

**Comment by sigmachirality** [comment]
As long as you don't actually provide people with the auth tokens, I don't see the harm in including the process in the README, as they wouldn't actually be able to connect to the DB. Also, if people were to setup a similar MongoDB DB they would be able to use the existing code to do the stuff. Reproducibility is important for maintaining the open source nature of your code.

**Comment by AndrooTheChen** [comment]
Updated.

**Comment by alexlee-hs** [comment]
> Updated.

K. I will merge now.

**Pull request merged**
